server.port=${SERVER_PORT:5193}

spring.datasource.url=jdbc:postgresql://localhost:5432/demo-security
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

batch.send.morning.emails.tasklet.active=true
batch.send.morning.emails.cron.expression=0 0 6 * * *
batch.default.zone=Europe/Rome

spring.batch.job.enabled=false

spring.mail.host=smtp.provider.com
spring.mail.port=587
spring.mail.username=your@domain.com
spring.mail.password=yourpassword
spring.mail.protocol=smtp

# opzioni JavaMail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# timeouts (millisecondi)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# mittente di default (opzionale)
app.mail.from=noreply@tuodominio.com

